project:
  type: website
  
website: 
  title: "VAA Team8 Project"
  navbar:
    left:
      - text: "Home"
        href: "VAA_Team8_Project.qmd"
      - text: "Proposal"
        href: "proposal.qmd"
      - text: "Analysis"
      - text: "Shiny APP"
        


format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual
