project:
  type: website
  
website: 
  title: "FIND or BE BLIND"
    
  navbar: 
    search: true
    left: 
      - text: "Home"
        href: "index.html"
      - text: "Proposal"
        href: "proposal/proposal.html"
      - text: "Shiny APP User Guide"
        href: "user_guide/shiny_user_guide.html"
      


format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual
